"use client";
import "../style/globals.css";
import Footer from "../components/footer";
import Navbar from "../components/navbar"

import { SessionProvider } from "next-auth/react";

// export const metadata = {
//   title: "articles",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </SessionProvider>
    </html>
  );
}
